spring:
  main:
    web-application-type: none
    banner-mode: off
  shell:
    command:
      completion:
        root-command: spring-up
      version:
        show-git-short-commit-id: true
  up:
    github:
      client-id: e4983cc3c5a6a2066b63

## disable console logging
logging:
  pattern:
    console:
## log debug from a cli
  file:
    name: shell.log
  level:
    # root: debug
    org:
      springframework:
        up: debug
        shell: debug
