name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17' ]
    name: CI Build ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: gradle
      - run: ./gradlew build --no-daemon
  native:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos
            os: macos-latest
            graal: 22.0.0.2
          - nickname: win
            os: windows-2019
            graal: 22.0.0.2
          - nickname: linux
            os: ubuntu-latest
            graal: 22.0.0.2
    name: CI Native ${{ matrix.graal }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 11
          components: native-image
          set-java-home: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build nativeCompile --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: spring-up-${{ matrix.nickname }}
          path: build/native/nativeCompile/
          retention-days: 1
      - name: Run Commands (linux/macos)
        run: |
          build/native/nativeCompile/spring-up version
        if: runner.os != 'Windows'
      - name: Run Commands (windows)
        run: |
          build/native/nativeCompile/spring-up.exe version
        if: runner.os == 'Windows'
